export const mockMovieData = [
    {   
        vote_count: 3119,
        id: 297802,
        video: false,
        vote_average: 6.9,
        title: "Aquaman",
        popularity: 483.065,
        poster_path: "/5Kg76ldv7VxeX9YlcQXiowHgdX6.jpg",
        original_language: "en",
        original_title: "Aquaman",
        backdrop_path: "/5A2bMlLfJrAfX9bqAibOL2gCruF.jpg",
        adult: false,
        overview: "Once home to the most advanced civilization on Earth, the city of Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people -- and then the surface world. Standing in his way is Aquaman, Orm's half-human, half-Atlantean brother and true heir to the throne. With help from royal counselor Vulko, Aquaman must retrieve the legendary Trident of Atlan and embrace his destiny as protector of the deep.",
        release_date: "2018-12-07",
    },
    {
        vote_count: 1020,
        id: 424783,
        video: false,
        vote_average: 6.5,
        title: "Bumblebee",
        popularity: 263.575,
        poster_path: "/fw02ONlDhrYjTSZV8XO6hhU3ds3.jpg",
        original_language: "en",
        original_title: "Bumblebee",
        backdrop_path: "/hMANgfPHR1tRObNp2oPiOi9mMlz.jpg",
        adult: false,
        overview: "On the run in the year 1987, Bumblebee finds refuge in a junkyard in a small Californian beach town. Charlie, on the cusp of turning 18 and trying to find her place in the world, discovers Bumblebee, battle-scarred and broken. When Charlie revives him, she quickly learns this is no ordinary yellow VW bug.",
        release_date: "2018-12-15",
    },
    { 
        vote_count: 829,
        id: 480530,
        video: false,
        vote_average: 6.6,
        title: "Creed II",
        popularity: 191.233,
        poster_path: "/v3QyboWRoA4O9RbcsqH8tJMe8EB.jpg",
        original_language: "en",
        original_title: "Creed II",
        backdrop_path: "/8yqLPNwNCtpOPc3XkOlkSMnghzw.jpg",
        adult: false,
        overview: "Follows Adonis Creed's life inside and outside of the ring as he deals with new found fame, issues with his family, and his continuing quest to become a champion.",
        release_date: "2018-11-21",
    }
]